services:
  backend:
    container_name: phonebook-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # Wait for the 'db' service to be healthy
    networks:
      - app_network

  db:
    container_name: phonebook-db
    image: postgres:16.9
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck: # This block tells Docker how to check if the DB is ready
      test: ["CMD-SHELL", "pg_isready -U postgres -d phonebook"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  nginx:
    image: nginx:stable-alpine
    ports:
      # Expose HTTP and HTTPS ports to the host machine
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - app_network
  
  # Frontend Service (React + Nginx)
  frontend:
    build:
      context: ./frontendnew/phonebook-frontend
      dockerfile: Dockerfile
    # No ports are exposed to the host machine.
    # The reverse-proxy communicates with this service over the internal docker network.
    networks:
      - app_network


# Define the network that allows containers to communicate with each other
networks:
  app_network:
    driver: bridge
