// This file is auto-generated by @hey-api/openapi-ts

export const AuthStatusSchema = {
    properties: {
        authenticated: {
            type: 'boolean',
            title: 'Authenticated'
        },
        isAdmin: {
            type: 'boolean',
            title: 'Isadmin'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['authenticated', 'isAdmin', 'email', 'name'],
    title: 'AuthStatus'
} as const;

export const BoardTypeSchema = {
    type: 'string',
    enum: ['institutional', 'executive'],
    title: 'BoardType'
} as const;

export const ConferenceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        }
    },
    type: 'object',
    required: ['name', 'start_date'],
    title: 'ConferenceCreate'
} as const;

export const ConferenceLiteResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'start_date', 'id'],
    title: 'ConferenceLiteResponse',
    description: 'A simplified schema for Conference, without nested relationships.'
} as const;

export const ConferenceResponseSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        talks: {
            items: {
                '$ref': '#/components/schemas/TalkResponse'
            },
            type: 'array',
            title: 'Talks',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'start_date', 'id'],
    title: 'ConferenceResponse'
} as const;

export const ConferenceUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        }
    },
    type: 'object',
    required: ['name', 'start_date'],
    title: 'ConferenceUpdate'
} as const;

export const ErrorDetailSchema = {
    properties: {
        detail: {
            type: 'string',
            title: 'Detail'
        },
        code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        }
    },
    type: 'object',
    required: ['detail'],
    title: 'ErrorDetail'
} as const;

export const GroupCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        date_created: {
            type: 'string',
            format: 'date',
            title: 'Date Created',
            default: '2025-08-05'
        },
        parent_group_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Group Id'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'GroupCreate'
} as const;

export const GroupLiteResponseSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'GroupLiteResponse',
    description: 'A simplified schema for Group, without nested relationships.'
} as const;

export const GroupMemberCreateSchema = {
    properties: {
        group_id: {
            type: 'integer',
            title: 'Group Id'
        },
        member_id: {
            type: 'integer',
            title: 'Member Id'
        },
        role_id: {
            type: 'integer',
            title: 'Role Id'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        }
    },
    type: 'object',
    required: ['group_id', 'member_id', 'role_id', 'start_date'],
    title: 'GroupMemberCreate'
} as const;

export const GroupMemberResponseSchema = {
    properties: {
        group_id: {
            type: 'integer',
            title: 'Group Id'
        },
        member_id: {
            type: 'integer',
            title: 'Member Id'
        },
        role_id: {
            type: 'integer',
            title: 'Role Id'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        group: {
            '$ref': '#/components/schemas/GroupLiteResponse'
        },
        member: {
            '$ref': '#/components/schemas/MemberLiteResponse'
        },
        role: {
            '$ref': '#/components/schemas/RoleResponse'
        }
    },
    type: 'object',
    required: ['group_id', 'member_id', 'role_id', 'start_date', 'id', 'group', 'member', 'role'],
    title: 'GroupMemberResponse',
    description: `Response schema for a group member entry.
Uses lite schemas for Group and Member to break the circular reference.`
} as const;

export const GroupResponseSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        parent_group: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/GroupLiteResponse'
                },
                {
                    type: 'null'
                }
            ]
        },
        subgroups: {
            items: {
                '$ref': '#/components/schemas/GroupLiteResponse'
            },
            type: 'array',
            title: 'Subgroups',
            default: []
        },
        group_memberships: {
            items: {
                '$ref': '#/components/schemas/GroupMemberResponse'
            },
            type: 'array',
            title: 'Group Memberships',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'GroupResponse',
    description: `Full response schema for a Group.
Uses lite schemas for parent/subgroups to prevent recursion.`
} as const;

export const GroupRoleSchema = {
    type: 'string',
    enum: ['members', 'convenor', 'co-convenor'],
    title: 'GroupRole'
} as const;

export const GroupUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        parent_group_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Group Id'
        }
    },
    type: 'object',
    title: 'GroupUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InstitutionCreateSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 50,
            title: 'Full Name'
        },
        short_name: {
            type: 'string',
            title: 'Short Name'
        },
        country: {
            type: 'string',
            title: 'Country'
        },
        region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        date_added: {
            type: 'string',
            format: 'date',
            title: 'Date Added'
        },
        date_removed: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Removed'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        entityid: {
            type: 'string',
            title: 'Entityid'
        },
        rorid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rorid'
        }
    },
    type: 'object',
    required: ['full_name', 'short_name', 'country', 'date_added', 'entityid'],
    title: 'InstitutionCreate'
} as const;

export const InstitutionLiteResponseSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 50,
            title: 'Full Name'
        },
        short_name: {
            type: 'string',
            title: 'Short Name'
        },
        country: {
            type: 'string',
            title: 'Country'
        },
        region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        date_added: {
            type: 'string',
            format: 'date',
            title: 'Date Added'
        },
        date_removed: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Removed'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        entityid: {
            type: 'string',
            title: 'Entityid'
        },
        rorid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rorid'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['full_name', 'short_name', 'country', 'date_added', 'entityid', 'id'],
    title: 'InstitutionLiteResponse',
    description: 'A simplified schema for Institution, without nested relationships.'
} as const;

export const InstitutionUpdateSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        short_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Short Name'
        },
        country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region'
        },
        latitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latitude'
        },
        longitude: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Longitude'
        },
        city: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        date_added: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Added'
        },
        date_removed: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Removed'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        rorid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rorid'
        }
    },
    type: 'object',
    title: 'InstitutionUpdate'
} as const;

export const InstitutionalBoardMemberCreateSchema = {
    properties: {
        member_id: {
            type: 'integer',
            title: 'Member Id'
        },
        institution_id: {
            type: 'integer',
            title: 'Institution Id'
        },
        board_type: {
            '$ref': '#/components/schemas/BoardType'
        },
        role_id: {
            type: 'integer',
            title: 'Role Id'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        }
    },
    type: 'object',
    required: ['member_id', 'institution_id', 'board_type', 'role_id', 'start_date'],
    title: 'InstitutionalBoardMemberCreate'
} as const;

export const InstitutionalBoardMemberResponseSchema = {
    properties: {
        member_id: {
            type: 'integer',
            title: 'Member Id'
        },
        institution_id: {
            type: 'integer',
            title: 'Institution Id'
        },
        board_type: {
            '$ref': '#/components/schemas/BoardType'
        },
        role_id: {
            type: 'integer',
            title: 'Role Id'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        member: {
            '$ref': '#/components/schemas/MemberLiteResponse'
        },
        institution: {
            '$ref': '#/components/schemas/InstitutionLiteResponse'
        },
        role: {
            '$ref': '#/components/schemas/RoleResponse'
        }
    },
    type: 'object',
    required: ['member_id', 'institution_id', 'board_type', 'role_id', 'start_date', 'id', 'member', 'institution', 'role'],
    title: 'InstitutionalBoardMemberResponse'
} as const;

export const InstitutionalBoardMemberUpdateSchema = {
    properties: {
        member_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Member Id'
        },
        institution_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Institution Id'
        },
        board_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BoardType'
                },
                {
                    type: 'null'
                }
            ]
        },
        role_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Id'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        }
    },
    type: 'object',
    title: 'InstitutionalBoardMemberUpdate'
} as const;

export const MemberCreateSchema = {
    properties: {
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        orcid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Orcid'
        },
        preferred_author_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Author Name'
        },
        institution_id: {
            type: 'integer',
            title: 'Institution Id'
        },
        date_joined: {
            type: 'string',
            format: 'date',
            title: 'Date Joined'
        },
        date_left: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Left'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        experimental_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experimental Data'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'email', 'institution_id', 'date_joined'],
    title: 'MemberCreate'
} as const;

export const MemberLiteResponseSchema = {
    properties: {
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        orcid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Orcid'
        },
        preferred_author_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Author Name'
        },
        institution_id: {
            type: 'integer',
            title: 'Institution Id'
        },
        date_joined: {
            type: 'string',
            format: 'date',
            title: 'Date Joined'
        },
        date_left: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Left'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        experimental_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experimental Data'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        institution: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InstitutionLiteResponse'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'email', 'institution_id', 'date_joined', 'id'],
    title: 'MemberLiteResponse',
    description: 'A simplified schema for Member, with basic institution details.'
} as const;

export const MemberUpdateSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        orcid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Orcid'
        },
        preferred_author_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preferred Author Name'
        },
        institution_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Institution Id'
        },
        date_joined: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Joined'
        },
        date_left: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Left'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        experimental_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experimental Data'
        }
    },
    type: 'object',
    title: 'MemberUpdate'
} as const;

export const PaginatedMemberResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/MemberLiteResponse'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        skip: {
            type: 'integer',
            title: 'Skip'
        },
        limit: {
            type: 'integer',
            title: 'Limit'
        }
    },
    type: 'object',
    required: ['items', 'total', 'skip', 'limit'],
    title: 'PaginatedMemberResponse'
} as const;

export const RoleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoleCreate'
} as const;

export const RoleResponseSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'RoleResponse'
} as const;

export const RoleUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'RoleUpdate'
} as const;

export const TalkAssignmentCreateSchema = {
    properties: {
        talk_id: {
            type: 'integer',
            title: 'Talk Id'
        },
        member_id: {
            type: 'integer',
            title: 'Member Id'
        },
        role_id: {
            type: 'integer',
            title: 'Role Id'
        },
        assigned_by_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigned By Id'
        }
    },
    type: 'object',
    required: ['talk_id', 'member_id', 'role_id'],
    title: 'TalkAssignmentCreate'
} as const;

export const TalkAssignmentResponseSchema = {
    properties: {
        talk_id: {
            type: 'integer',
            title: 'Talk Id'
        },
        member_id: {
            type: 'integer',
            title: 'Member Id'
        },
        role_id: {
            type: 'integer',
            title: 'Role Id'
        },
        assigned_by_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigned By Id'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        member: {
            '$ref': '#/components/schemas/MemberLiteResponse'
        },
        role: {
            '$ref': '#/components/schemas/RoleResponse'
        },
        assigned_by_member: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MemberLiteResponse'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['talk_id', 'member_id', 'role_id', 'id', 'member', 'role'],
    title: 'TalkAssignmentResponse'
} as const;

export const TalkAssignmentUpdateSchema = {
    properties: {
        talk_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Talk Id'
        },
        member_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Member Id'
        },
        role_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Id'
        },
        assigned_by_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigned By Id'
        }
    },
    type: 'object',
    title: 'TalkAssignmentUpdate'
} as const;

export const TalkCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        docdb_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Docdb Id'
        },
        talk_link: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Talk Link'
        },
        conference_id: {
            type: 'integer',
            title: 'Conference Id'
        }
    },
    type: 'object',
    required: ['title', 'start_date', 'conference_id'],
    title: 'TalkCreate'
} as const;

export const TalkLiteResponseSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        docdb_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Docdb Id'
        },
        talk_link: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Talk Link'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['title', 'start_date', 'id'],
    title: 'TalkLiteResponse'
} as const;

export const TalkResponseSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        docdb_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Docdb Id'
        },
        talk_link: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Talk Link'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        assignments: {
            items: {
                '$ref': '#/components/schemas/TalkAssignmentResponse'
            },
            type: 'array',
            title: 'Assignments',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'start_date', 'id'],
    title: 'TalkResponse'
} as const;

export const TalkUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        docdb_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Docdb Id'
        },
        talk_link: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Talk Link'
        },
        conference_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conference Id'
        }
    },
    type: 'object',
    required: ['title', 'start_date'],
    title: 'TalkUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;