// This file is auto-generated by @hey-api/openapi-ts

import type { InstitutionsListInstitutionsResponse, InstitutionsCreateInstitutionResponse, InstitutionsGetInstitutionResponse, InstitutionsUpdateInstitutionResponse, InstitutionsGetInstitutionMembersResponse, MembersListMembersResponse, MembersCreateMemberResponse, MembersGetMemberResponse, MembersUpdateMemberResponse, BoardMembersListBoardMembershipsResponse, BoardMembersCreateBoardMembershipResponse, BoardMembersGetBoardMembershipResponse, BoardMembersUpdateBoardMembershipResponse, WorkingGroupsCreateGroupResponse, WorkingGroupsGetGroupResponse, WorkingGroupsUpdateGroupResponse, WorkingGroupsListGroupMembersOfGroupResponse, WorkingGroupsAddMemberToGroupResponse, ConferencesListConferencesResponse, ConferencesCreateConferenceResponse, ConferencesGetConferenceResponse, ConferencesUpdateConferenceResponse, TalksListTalksResponse, TalksCreateTalkResponse, TalksGetTalkResponse, TalksUpdateTalkResponse, TalkAssignmentsListTalkAssignmentsResponse, TalkAssignmentsCreateTalkAssignmentResponse, TalkAssignmentsGetTalkAssignmentResponse, TalkAssignmentsUpdateTalkAssignmentResponse } from './types.gen';

const institutionLiteResponseSchemaResponseTransformer = (data: any) => {
    data.date_added = new Date(data.date_added);
    if (data.date_removed) {
        data.date_removed = new Date(data.date_removed);
    }
    return data;
};

export const institutionsListInstitutionsResponseTransformer = async (data: any): Promise<InstitutionsListInstitutionsResponse> => {
    data = data.map((item: any) => {
        return institutionLiteResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const institutionsCreateInstitutionResponseTransformer = async (data: any): Promise<InstitutionsCreateInstitutionResponse> => {
    data = institutionLiteResponseSchemaResponseTransformer(data);
    return data;
};

export const institutionsGetInstitutionResponseTransformer = async (data: any): Promise<InstitutionsGetInstitutionResponse> => {
    data = institutionLiteResponseSchemaResponseTransformer(data);
    return data;
};

export const institutionsUpdateInstitutionResponseTransformer = async (data: any): Promise<InstitutionsUpdateInstitutionResponse> => {
    data = institutionLiteResponseSchemaResponseTransformer(data);
    return data;
};

const memberLiteResponseSchemaResponseTransformer = (data: any) => {
    data.date_joined = new Date(data.date_joined);
    if (data.date_left) {
        data.date_left = new Date(data.date_left);
    }
    if (data.institution) {
        data.institution = institutionLiteResponseSchemaResponseTransformer(data.institution);
    }
    return data;
};

export const institutionsGetInstitutionMembersResponseTransformer = async (data: any): Promise<InstitutionsGetInstitutionMembersResponse> => {
    data = data.map((item: any) => {
        return memberLiteResponseSchemaResponseTransformer(item);
    });
    return data;
};

const paginatedMemberResponseSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => {
        return memberLiteResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const membersListMembersResponseTransformer = async (data: any): Promise<MembersListMembersResponse> => {
    data = paginatedMemberResponseSchemaResponseTransformer(data);
    return data;
};

export const membersCreateMemberResponseTransformer = async (data: any): Promise<MembersCreateMemberResponse> => {
    data = memberLiteResponseSchemaResponseTransformer(data);
    return data;
};

export const membersGetMemberResponseTransformer = async (data: any): Promise<MembersGetMemberResponse> => {
    data = memberLiteResponseSchemaResponseTransformer(data);
    return data;
};

export const membersUpdateMemberResponseTransformer = async (data: any): Promise<MembersUpdateMemberResponse> => {
    data = memberLiteResponseSchemaResponseTransformer(data);
    return data;
};

const institutionalBoardMemberResponseSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    data.member = memberLiteResponseSchemaResponseTransformer(data.member);
    data.institution = institutionLiteResponseSchemaResponseTransformer(data.institution);
    return data;
};

export const boardMembersListBoardMembershipsResponseTransformer = async (data: any): Promise<BoardMembersListBoardMembershipsResponse> => {
    data = data.map((item: any) => {
        return institutionalBoardMemberResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const boardMembersCreateBoardMembershipResponseTransformer = async (data: any): Promise<BoardMembersCreateBoardMembershipResponse> => {
    data = institutionalBoardMemberResponseSchemaResponseTransformer(data);
    return data;
};

export const boardMembersGetBoardMembershipResponseTransformer = async (data: any): Promise<BoardMembersGetBoardMembershipResponse> => {
    data = institutionalBoardMemberResponseSchemaResponseTransformer(data);
    return data;
};

export const boardMembersUpdateBoardMembershipResponseTransformer = async (data: any): Promise<BoardMembersUpdateBoardMembershipResponse> => {
    data = institutionalBoardMemberResponseSchemaResponseTransformer(data);
    return data;
};

const groupMemberResponseSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    data.member = memberLiteResponseSchemaResponseTransformer(data.member);
    return data;
};

const groupResponseSchemaResponseTransformer = (data: any) => {
    if (data.group_memberships) {
        data.group_memberships = data.group_memberships.map((item: any) => {
            return groupMemberResponseSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const workingGroupsCreateGroupResponseTransformer = async (data: any): Promise<WorkingGroupsCreateGroupResponse> => {
    data = groupResponseSchemaResponseTransformer(data);
    return data;
};

export const workingGroupsGetGroupResponseTransformer = async (data: any): Promise<WorkingGroupsGetGroupResponse> => {
    data = groupResponseSchemaResponseTransformer(data);
    return data;
};

export const workingGroupsUpdateGroupResponseTransformer = async (data: any): Promise<WorkingGroupsUpdateGroupResponse> => {
    data = groupResponseSchemaResponseTransformer(data);
    return data;
};

export const workingGroupsListGroupMembersOfGroupResponseTransformer = async (data: any): Promise<WorkingGroupsListGroupMembersOfGroupResponse> => {
    data = data.map((item: any) => {
        return groupMemberResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const workingGroupsAddMemberToGroupResponseTransformer = async (data: any): Promise<WorkingGroupsAddMemberToGroupResponse> => {
    data = groupMemberResponseSchemaResponseTransformer(data);
    return data;
};

const conferenceLiteResponseSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    return data;
};

export const conferencesListConferencesResponseTransformer = async (data: any): Promise<ConferencesListConferencesResponse> => {
    data = data.map((item: any) => {
        return conferenceLiteResponseSchemaResponseTransformer(item);
    });
    return data;
};

const talkAssignmentResponseSchemaResponseTransformer = (data: any) => {
    data.member = memberLiteResponseSchemaResponseTransformer(data.member);
    if (data.assigned_by_member) {
        data.assigned_by_member = memberLiteResponseSchemaResponseTransformer(data.assigned_by_member);
    }
    return data;
};

const talkResponseSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    if (data.assignments) {
        data.assignments = data.assignments.map((item: any) => {
            return talkAssignmentResponseSchemaResponseTransformer(item);
        });
    }
    return data;
};

const conferenceResponseSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    if (data.talks) {
        data.talks = data.talks.map((item: any) => {
            return talkResponseSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const conferencesCreateConferenceResponseTransformer = async (data: any): Promise<ConferencesCreateConferenceResponse> => {
    data = conferenceResponseSchemaResponseTransformer(data);
    return data;
};

export const conferencesGetConferenceResponseTransformer = async (data: any): Promise<ConferencesGetConferenceResponse> => {
    data = conferenceResponseSchemaResponseTransformer(data);
    return data;
};

export const conferencesUpdateConferenceResponseTransformer = async (data: any): Promise<ConferencesUpdateConferenceResponse> => {
    data = conferenceResponseSchemaResponseTransformer(data);
    return data;
};

const talkLiteResponseSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    return data;
};

export const talksListTalksResponseTransformer = async (data: any): Promise<TalksListTalksResponse> => {
    data = data.map((item: any) => {
        return talkLiteResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const talksCreateTalkResponseTransformer = async (data: any): Promise<TalksCreateTalkResponse> => {
    data = talkResponseSchemaResponseTransformer(data);
    return data;
};

export const talksGetTalkResponseTransformer = async (data: any): Promise<TalksGetTalkResponse> => {
    data = talkResponseSchemaResponseTransformer(data);
    return data;
};

export const talksUpdateTalkResponseTransformer = async (data: any): Promise<TalksUpdateTalkResponse> => {
    data = talkResponseSchemaResponseTransformer(data);
    return data;
};

export const talkAssignmentsListTalkAssignmentsResponseTransformer = async (data: any): Promise<TalkAssignmentsListTalkAssignmentsResponse> => {
    data = data.map((item: any) => {
        return talkAssignmentResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const talkAssignmentsCreateTalkAssignmentResponseTransformer = async (data: any): Promise<TalkAssignmentsCreateTalkAssignmentResponse> => {
    data = talkAssignmentResponseSchemaResponseTransformer(data);
    return data;
};

export const talkAssignmentsGetTalkAssignmentResponseTransformer = async (data: any): Promise<TalkAssignmentsGetTalkAssignmentResponse> => {
    data = talkAssignmentResponseSchemaResponseTransformer(data);
    return data;
};

export const talkAssignmentsUpdateTalkAssignmentResponseTransformer = async (data: any): Promise<TalkAssignmentsUpdateTalkAssignmentResponse> => {
    data = talkAssignmentResponseSchemaResponseTransformer(data);
    return data;
};