// This file is auto-generated by @hey-api/openapi-ts

import type { InstitutionsListInstitutionsResponse, InstitutionsCreateInstitutionResponse, InstitutionsGetInstitutionResponse, InstitutionsUpdateInstitutionResponse, MembersListMembersResponse, MembersCreateMemberResponse, MembersGetMemberResponse, MembersUpdateMemberResponse, BoardMembersListBoardMembershipsResponse, BoardMembersCreateBoardMembershipResponse, BoardMembersGetBoardMembershipResponse, BoardMembersUpdateBoardMembershipResponse } from './types.gen';

const institutionResponseSchemaResponseTransformer = (data: any) => {
    data.date_added = new Date(data.date_added);
    if (data.date_removed) {
        data.date_removed = new Date(data.date_removed);
    }
    return data;
};

export const institutionsListInstitutionsResponseTransformer = async (data: any): Promise<InstitutionsListInstitutionsResponse> => {
    data = data.map((item: any) => {
        return institutionResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const institutionsCreateInstitutionResponseTransformer = async (data: any): Promise<InstitutionsCreateInstitutionResponse> => {
    data = institutionResponseSchemaResponseTransformer(data);
    return data;
};

export const institutionsGetInstitutionResponseTransformer = async (data: any): Promise<InstitutionsGetInstitutionResponse> => {
    data = institutionResponseSchemaResponseTransformer(data);
    return data;
};

export const institutionsUpdateInstitutionResponseTransformer = async (data: any): Promise<InstitutionsUpdateInstitutionResponse> => {
    data = institutionResponseSchemaResponseTransformer(data);
    return data;
};

const memberResponseSchemaResponseTransformer = (data: any) => {
    data.date_joined = new Date(data.date_joined);
    if (data.date_left) {
        data.date_left = new Date(data.date_left);
    }
    if (data.institution) {
        data.institution = institutionResponseSchemaResponseTransformer(data.institution);
    }
    return data;
};

export const membersListMembersResponseTransformer = async (data: any): Promise<MembersListMembersResponse> => {
    data = data.map((item: any) => {
        return memberResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const membersCreateMemberResponseTransformer = async (data: any): Promise<MembersCreateMemberResponse> => {
    data = memberResponseSchemaResponseTransformer(data);
    return data;
};

export const membersGetMemberResponseTransformer = async (data: any): Promise<MembersGetMemberResponse> => {
    data = memberResponseSchemaResponseTransformer(data);
    return data;
};

export const membersUpdateMemberResponseTransformer = async (data: any): Promise<MembersUpdateMemberResponse> => {
    data = memberResponseSchemaResponseTransformer(data);
    return data;
};

const institutionalBoardMemberResponseSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    return data;
};

export const boardMembersListBoardMembershipsResponseTransformer = async (data: any): Promise<BoardMembersListBoardMembershipsResponse> => {
    data = data.map((item: any) => {
        return institutionalBoardMemberResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const boardMembersCreateBoardMembershipResponseTransformer = async (data: any): Promise<BoardMembersCreateBoardMembershipResponse> => {
    data = institutionalBoardMemberResponseSchemaResponseTransformer(data);
    return data;
};

export const boardMembersGetBoardMembershipResponseTransformer = async (data: any): Promise<BoardMembersGetBoardMembershipResponse> => {
    data = institutionalBoardMemberResponseSchemaResponseTransformer(data);
    return data;
};

export const boardMembersUpdateBoardMembershipResponseTransformer = async (data: any): Promise<BoardMembersUpdateBoardMembershipResponse> => {
    data = institutionalBoardMemberResponseSchemaResponseTransformer(data);
    return data;
};