// This file is auto-generated by @hey-api/openapi-ts

import type { InstitutionsListInstitutionsResponse, InstitutionsCreateInstitutionResponse, InstitutionsGetInstitutionResponse, InstitutionsUpdateInstitutionResponse, InstitutionsGetInstitutionMembersResponse, MembersListMembersResponse, MembersCreateMemberResponse, MembersGetMemberResponse, MembersUpdateMemberResponse, BoardMembersListBoardMembershipsResponse, BoardMembersCreateBoardMembershipResponse, BoardMembersGetBoardMembershipResponse, BoardMembersUpdateBoardMembershipResponse, WorkingGroupsCreateGroupResponse, WorkingGroupsGetGroupResponse, WorkingGroupsUpdateGroupResponse, WorkingGroupsListGroupMembersOfGroupResponse, WorkingGroupsAddMemberToGroupResponse } from './types.gen';

const institutionLiteResponseSchemaResponseTransformer = (data: any) => {
    data.date_added = new Date(data.date_added);
    if (data.date_removed) {
        data.date_removed = new Date(data.date_removed);
    }
    return data;
};

export const institutionsListInstitutionsResponseTransformer = async (data: any): Promise<InstitutionsListInstitutionsResponse> => {
    data = data.map((item: any) => {
        return institutionLiteResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const institutionsCreateInstitutionResponseTransformer = async (data: any): Promise<InstitutionsCreateInstitutionResponse> => {
    data = institutionLiteResponseSchemaResponseTransformer(data);
    return data;
};

export const institutionsGetInstitutionResponseTransformer = async (data: any): Promise<InstitutionsGetInstitutionResponse> => {
    data = institutionLiteResponseSchemaResponseTransformer(data);
    return data;
};

export const institutionsUpdateInstitutionResponseTransformer = async (data: any): Promise<InstitutionsUpdateInstitutionResponse> => {
    data = institutionLiteResponseSchemaResponseTransformer(data);
    return data;
};

const memberLiteResponseSchemaResponseTransformer = (data: any) => {
    data.date_joined = new Date(data.date_joined);
    if (data.date_left) {
        data.date_left = new Date(data.date_left);
    }
    if (data.institution) {
        data.institution = institutionLiteResponseSchemaResponseTransformer(data.institution);
    }
    return data;
};

export const institutionsGetInstitutionMembersResponseTransformer = async (data: any): Promise<InstitutionsGetInstitutionMembersResponse> => {
    data = data.map((item: any) => {
        return memberLiteResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const membersListMembersResponseTransformer = async (data: any): Promise<MembersListMembersResponse> => {
    data = data.map((item: any) => {
        return memberLiteResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const membersCreateMemberResponseTransformer = async (data: any): Promise<MembersCreateMemberResponse> => {
    data = memberLiteResponseSchemaResponseTransformer(data);
    return data;
};

export const membersGetMemberResponseTransformer = async (data: any): Promise<MembersGetMemberResponse> => {
    data = memberLiteResponseSchemaResponseTransformer(data);
    return data;
};

export const membersUpdateMemberResponseTransformer = async (data: any): Promise<MembersUpdateMemberResponse> => {
    data = memberLiteResponseSchemaResponseTransformer(data);
    return data;
};

const institutionalBoardMemberResponseSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    data.member = memberLiteResponseSchemaResponseTransformer(data.member);
    data.institution = institutionLiteResponseSchemaResponseTransformer(data.institution);
    return data;
};

export const boardMembersListBoardMembershipsResponseTransformer = async (data: any): Promise<BoardMembersListBoardMembershipsResponse> => {
    data = data.map((item: any) => {
        return institutionalBoardMemberResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const boardMembersCreateBoardMembershipResponseTransformer = async (data: any): Promise<BoardMembersCreateBoardMembershipResponse> => {
    data = institutionalBoardMemberResponseSchemaResponseTransformer(data);
    return data;
};

export const boardMembersGetBoardMembershipResponseTransformer = async (data: any): Promise<BoardMembersGetBoardMembershipResponse> => {
    data = institutionalBoardMemberResponseSchemaResponseTransformer(data);
    return data;
};

export const boardMembersUpdateBoardMembershipResponseTransformer = async (data: any): Promise<BoardMembersUpdateBoardMembershipResponse> => {
    data = institutionalBoardMemberResponseSchemaResponseTransformer(data);
    return data;
};

const groupMemberResponseSchemaResponseTransformer = (data: any) => {
    data.start_date = new Date(data.start_date);
    if (data.end_date) {
        data.end_date = new Date(data.end_date);
    }
    data.member = memberLiteResponseSchemaResponseTransformer(data.member);
    return data;
};

const groupResponseSchemaResponseTransformer = (data: any) => {
    if (data.group_memberships) {
        data.group_memberships = data.group_memberships.map((item: any) => {
            return groupMemberResponseSchemaResponseTransformer(item);
        });
    }
    return data;
};

export const workingGroupsCreateGroupResponseTransformer = async (data: any): Promise<WorkingGroupsCreateGroupResponse> => {
    data = groupResponseSchemaResponseTransformer(data);
    return data;
};

export const workingGroupsGetGroupResponseTransformer = async (data: any): Promise<WorkingGroupsGetGroupResponse> => {
    data = groupResponseSchemaResponseTransformer(data);
    return data;
};

export const workingGroupsUpdateGroupResponseTransformer = async (data: any): Promise<WorkingGroupsUpdateGroupResponse> => {
    data = groupResponseSchemaResponseTransformer(data);
    return data;
};

export const workingGroupsListGroupMembersOfGroupResponseTransformer = async (data: any): Promise<WorkingGroupsListGroupMembersOfGroupResponse> => {
    data = data.map((item: any) => {
        return groupMemberResponseSchemaResponseTransformer(item);
    });
    return data;
};

export const workingGroupsAddMemberToGroupResponseTransformer = async (data: any): Promise<WorkingGroupsAddMemberToGroupResponse> => {
    data = groupMemberResponseSchemaResponseTransformer(data);
    return data;
};